In [1]:
include("/Users/00eila01/01_Arbete/UTBILDNING/KEXET/Numerical-Solutions-and-Parameter-Sensitivity-of-the-Lorentz-System-Degree-Project-in-Technology/Numerical-Solvers/Solvers.jl")
include("/Users/00eila01/01_Arbete/UTBILDNING/KEXET/Numerical-Solutions-and-Parameter-Sensitivity-of-the-Lorentz-System-Degree-Project-in-Technology/Numerical-Solvers/UsefulFunctions.jl")
include("/Users/00eila01/01_Arbete/UTBILDNING/KEXET/Numerical-Solutions-and-Parameter-Sensitivity-of-the-Lorentz-System-Degree-Project-in-Technology/Numerical-Solvers/PointGenerators.jl")

PointsOnSphere (generic function with 2 methods)

In [2]:
using DifferentialEquations

In [93]:
function CorrelationMatrix_Initpos(p,Δt,N,initial_points,Solver,center)
    M = zeros(length(initial_points[1,:]), N+1)
    for i = 1:length(initial_points[1,:])
        x₀ = initial_points[:,i]
        X = []
        push!(X,LorenzSolutionFixedTimeStep(p, Δt, N, x₀, Solver))
        push!(X,LorenzSolutionFixedTimeStep(p, Δt, N, center, Solver))
        for j = 1:N+1
            M[i,j] = Correlation(X[1][:,j], X[2][:,j])
        end
    end
    return M
end

CorrelationMatrix_Initpos (generic function with 1 method)

In [52]:
# initial conditions
x₀ = [0.0; 
     1.0; 
     0.0]
θ = 10; μ = 28; β = 8/3;
p=[θ,μ,β]
t = 5
Δt = 10^(-4)

0.0001

In [25]:
epsilon_vals = [10^(-10), 10^(-9)]

2-element Vector{BigFloat}:
 1.0000000000000000364321973154977415791655470655996396089904010295867919921875e-10
 1.0000000000000000622815914577798564188970686927859787829220294952392578125e-09

In [107]:
initial_vals = PointsOnSphere(100, 0.5, x₀')

3×100 Matrix{Float64}:
 -0.343507   0.328751  -0.304342  …  -0.31134   0.0917318  -0.385113
  0.880655   1.0324     0.964084      0.985921  0.510764    1.31838
 -0.343161  -0.37533   -0.395077      0.390985  0.0472558   0.0178818

In [77]:
length(initial_vals[1,:])

100

In [108]:
CorrelationMatrix_Initpos(p,Δt,30,initial_vals,RK4,x₀)

100×31 Matrix{Float64}:
 0.875717  0.875512  0.875308  0.875104  …  0.8703    0.870119  0.86994
 0.900365  0.900664  0.900963  0.901262     0.908589  0.908876  0.909162
 0.888201  0.888048  0.887896  0.887744     0.884229  0.8841    0.883971
 0.866048  0.865806  0.865566  0.865327     0.859635  0.85942   0.859206
 0.963711  0.96379   0.96387   0.96395      0.96597   0.966052  0.966133
 0.86658   0.866397  0.866214  0.866033  …  0.861786  0.861628  0.861471
 0.867929  0.867836  0.867744  0.867653     0.865671  0.865604  0.865538
 0.926926  0.92691   0.926894  0.926879     0.926676  0.926675  0.926675
 0.99177   0.991773  0.991775  0.991778     0.991861  0.991865  0.991869
 0.873615  0.87407   0.874524  0.874977     0.885926  0.886349  0.886771
 ⋮                                       ⋱                      ⋮
 0.867214  0.867511  0.867808  0.868105     0.875486  0.875779  0.876071
 0.926595  0.926506  0.926418  0.926331     0.924417  0.924352  0.924287
 0.887585  0.887949  0.888313  0.88

In [70]:
LorenzSolutionFixedTimeStep(p, Δt, 5, initial_vals[:,1], RK4)

3×6 Matrix{Float64}:
  4.09092e-11  0.000999451  0.00199781  0.00299507  0.00399124  0.00498633
  1.0          0.999901     0.999806    0.999713    0.999622    0.999535
 -4.88208e-11  4.99251e-8   1.99743e-7  4.49251e-7  7.98294e-7  1.24672e-6